version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Paris"
    cooldown:
      default-days: 1
    open-pull-requests-limit: 5
    labels:
      - "type: dependencies"
      - "status: needs-review"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@eslint/js"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint-plugin-astro"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:30"
      timezone: "Europe/Paris"
    cooldown:
      default-days: 1
    open-pull-requests-limit: 5
    labels:
      - "type: dependencies"
      - "area: tooling"
      - "status: needs-review"
    commit-message:
      prefix: "chore"
      include: "scope"
