# Project information
site_author: c2tz
site_description: Blog, notes et docs de c2tz.
site_name: "Blog de c2tz"
site_url: "https://blog.cta.li/"
edit_uri: edit/main/docs/

# Configuration
theme:
  custom_dir: custom
  direction: ltr
  language: fr
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    # desactiver les polices et overide le block font avec mon fichier .woff2
    #false
    text: Roboto
    code: Roboto Mono
  icon:
    repo: simple/github
    annotation: material/arrow-right-circle
  # Color
  palette:
      scheme: slate
      primary: custom
      accent: black
  watch:
    - includes
  # Feature
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    # - content.tooltips
    - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: ''
      permalink_title: Permalien
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: c2tz
      repo: blog.cta.li
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

# Repository information
repo_name: c2tz/blog.cta.li
repo_url: https://github.com/c2tz/blog.cta.li

# Page tree
nav:
  - Blog: index.md

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Europe/Paris
      type: timeago
      locale: fr
      fallback_to_build_date: true
  - privacy:
      enabled: !ENV [CI, false]
  - optimize:
      enabled: !ENV [CI, false]
  - glightbox
  - git-committers:
      repository: c2tz/blog.cta.li
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - blog:
      blog_dir: .
      blog_toc: false
      post_date_format: full
      post_excerpt: required
      post_readtime: true
      post_readtime_words_per_minute: 250
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

# Custom
extra_css:
  - stylesheets/extra.css

# Footer
extra:
  generator: false
  social:
    - icon: simple/bluesky
      link: https://bsky.app/profile/c2tz.bsky.social
    - icon: fontawesome/brands/github
      link: https://github.com/c2tz
    - icon: simple/matrix
      link: https://matrix.to/#/@c2tz:matrix.org
    - icon: simple/youtube
      link: https://youtube.com/@c2tz
    - icon: fontawesome/solid/earth-europe
      link: https://cta.li/
    - icon: simple/protonmail
      link: mailto:ctailliez@cta.li
    - icon: simple/keeweb
      link: https://iez.cta.li/publickey.ctailliez@cta.li-5ddcb7b94817b035c31f8e538d74276dafc53cad.asc
      
copyright: Aucun droit réservé - c2tz <br> Fait avec <a href="https://squidfunk.github.io/mkdocs-material" target="_blank" rel="noreferrer noopener">Material for MkDocs </a> et propulsé par <a href="https://github.com/" target="_blank" rel="noreferrer noopener">GitHub Pages</a>  
